name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 依存関係をインストールしてビルド
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # AWS CLI の設定
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1 # 東京リージョン

      # S3 へアップロード
      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://tora29-lab-svelte-app --delete

      # CloudFront キャッシュを無効化
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1R35ZBJGN3OBW --paths "/*"
