name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Node.js のセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Astro 用に静的アセットをコピー
        run: |
          mkdir -p public
          cp -R src/shared/static/* public/

      - name: 依存関係をインストールしてビルド
        run: |
          npm ci
          npm run astro-build

      - name: Terraform のセットアップ
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.4

      - name: Terraform の初期化
        run: |
          cd terraform
          terraform init

      - name: Terraform の準備
        run: |
          cd terraform
          terraform plan -out=tfplan

      - name: Terraform の実行
        run: |
          cd terraform
          terraform apply -auto-approve tfplan

      - name: S3 へアップロード
        run: |
          aws s3 sync ./dist s3://tora29-lab-svelte-app --delete

      - name: CloudFront キャッシュを無効化
        run: |
          aws cloudfront create-invalidation --distribution-id E1R35ZBJGN3OBW --paths "/*"
